src/Entity/Ingredients.php
<?php

namespace App\Entity;

use App\Repository\IngredientsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=IngredientsRepository::class)
 */
class Ingredients
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $common_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $botanic_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $family;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $use_part;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $under_group;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommonName(): ?string
    {
        return $this->common_name;
    }

    public function setCommonName(string $common_name): self
    {
        $this->common_name = $common_name;

        return $this;
    }

    public function getBotanicName(): ?string
    {
        return $this->botanic_name;
    }

    public function setBotanicName(string $botanic_name): self
    {
        $this->botanic_name = $botanic_name;

        return $this;
    }

    public function getFamily(): ?string
    {
        return $this->family;
    }

    public function setFamily(string $family): self
    {
        $this->family = $family;

        return $this;
    }

    public function getUsePart(): ?string
    {
        return $this->use_part;
    }

    public function setUsePart(string $use_part): self
    {
        $this->use_part = $use_part;

        return $this;
    }

    public function getUnderGroup(): ?string
    {
        return $this->under_group;
    }

    public function setUnderGroup(string $under_group): self
    {
        $this->under_group = $under_group;

        return $this;
    }
}

src/Form/IngredientsType.php
<?php

namespace App\Form;

use App\Entity\Ingredients;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IngredientsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('common_name')
            ->add('botanic_name')
            ->add('family')
            ->add('use_part')
            ->add('under_group')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ingredients::class,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Ingredients;
use App\Form\IngredientsType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="app_home")
     */
    public function index(Request $request, EntityManagerInterface $entityManager): Response
    {
        $ingredient =new Ingredients();
        $form = $this->createForm(IngredientsType::class, $ingredient);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $ingredient =$form->getData();
            $entityManager->persist($ingredient);
            $entityManager->flush();

            return $this->redirectToRoute('app_page1');
        }
        return $this->render('home/index.html.twig',[
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/PageController.php
<?php

namespace App\Controller;

use App\Repository\IngredientsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PageController extends AbstractController
{
    /**
     * @Route("/page1", name="app_page1")
     */
    public function index1(IngredientsRepository $ingredientsRepository): Response
    {
        $ingredients = $ingredientsRepository->findAll();

        return $this->render('page1/index.html.twig', [
            'ingredients' => $ingredients
        ]);
    }

    /**
     * @Route("/page2", name="app_page2")
     */
    public function index2(): Response
    {
        return $this->render('page2/index.html.twig');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
    <nav>
        <a href="{{ path('app_home') }}">Accueil</a>
        <a href="{{ path('app_page1') }}"> | Page 1</a>
        <a href="{{ path('app_page2') }}"> | Page 2</a>
    </nav>
        {% block body %}{% endblock %}
    </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paf le test{% endblock %}

{% block body %}
    <h1 style="text-align: center">Et Paf!!! le Test</h1>

    <p>D'ailleurs, un test qui fonctionne bien.</p>

    <p>remplissons ce formulaire d'ingredients afin de voir si la base de donnée fonctionne également: </p>
{{ form_start(form) }}
    {{ form_widget(form.common_name,{'attr': {'placeholder': 'Nom commun' } }) }}<br>
    {{ form_widget(form.botanic_name,{'attr': {'placeholder': 'Nom botanique' } }) }}<br>
    {{ form_widget(form.family,{'attr': {'placeholder': 'Famille' } }) }}<br>
    {{ form_widget(form.use_part,{'attr': {'placeholder': 'Partie utilisée' } }) }}<br>
    {{ form_widget(form.under_group,{'attr': {'placeholder': 'Sous groupe' } }) }}<br>
    <button type="submit" class="btn btn-outline-primary">
        Enregistrer
    </button>
{{ form_end(form) }}

{% endblock %}

templates/page1/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Page 1{% endblock %}

{% block body %}
<h1 style="text-align: center">Page 1</h1>
    <h2>Codex Alimentarius</h2>
    {% for ingredient in ingredients %}
        <h3>{{ ingredient.commonName }}</h3>
        {{ ingredient.botanicName }} | {{ ingredient.family }} | {{ ingredient.underGroup }} | {{ ingredient.usePart }}<br><br>
    {% endfor %}
    <p> " Bim Boum!!! " c'est une test page</p>
{% endblock %}

templates/page2/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Page 2{% endblock %}

{% block body %}
    <h1 style="text-align: center">Page 2</h1>
    <p>" Pif Paf!!!! " c'est encore une test page</p>
{% endblock %}